import Link from 'next/link'
import Image from 'next/image'
import { ArrowUpRight, Check } from 'lucide-react'
import { GlobalShell } from '@/components/site-shell'
import { RoiCalculator } from '@/components/roi-calculator'

const services = ['Optimización de ingresos', 'Sincronización total', 'Gestión de huéspedes', 'Cumplimiento legal', 'Gestión de cobros', 'Informes detallados']
export default function GestionPage() { return <GlobalShell><main className="content-page"><section className="service-hero"><Image src="https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=1800&q=85" alt="Casa mediterránea para alquiler vacacional" fill sizes="100vw" className="hero-image" /><div className="hero-overlay" /><div className="container hero-content"><p className="eyebrow eyebrow-light">GESTIÓN VACACIONAL</p><h1>Gestión profesional de alquiler vacacional</h1><p className="hero-copy">Mejora la gestión y el rendimiento potencial de tu propiedad mientras nosotros coordinamos el día a día.</p><Link className="button button-gold" href="/contacto">Solicitar información <ArrowUpRight size={16} /></Link></div></section><section className="section"><div className="container"><div className="center-heading"><p className="eyebrow">GESTIÓN 360°</p><h2>¿Qué incluye nuestro <em>servicio?</em></h2><p>Para que tú solo te preocupes de recibir tus ingresos.</p></div><div className="service-grid">{services.map((service, index) => <article className="service-card" key={service}><Check size={20} /><h3>{service}</h3><p>{['Precios dinámicos basados en demanda y temporada.', 'Conexión con las principales plataformas.', 'Atención, check-in, limpieza y mantenimiento.', 'Registro de viajeros, tasas y licencias.', 'Gestión de pagos y transferencias.', 'Estadísticas de ocupación, ingresos y rendimiento.'][index]}</p></article>)}</div></div></section><section className="section plans-section"><div className="container"><div className="center-heading"><p className="eyebrow">PLANES DE GESTIÓN</p><h2>Elige el plan que mejor se adapte a <em>tus necesidades.</em></h2></div><div className="plans-grid"><Plan name="Premium" description="Gestión completa sin preocupaciones" items={['Publicación en plataformas', 'Sincronización de calendarios', 'Gestión de reservas', 'Atención al cliente', 'Informes mensuales', 'Limpieza profesional', 'Check-in/check-out presencial', 'Mantenimiento incluido', 'Optimización de precios', 'Fotografía profesional', 'Registro de viajeros', 'Gestión de la tasa turística']} /><Plan name="Exclusive" description="Servicio VIP para propiedades de lujo" items={['Todo lo incluido en el plan Premium', 'Servicios de conserjería', 'Amenities premium', 'Marketing personalizado', 'Atención prioritaria 24/7', 'Gestor personal dedicado']} /></div></div></section><section className="section"><div className="container"><RoiCalculator /></div></section><section className="final-cta"><div className="container final-cta-inner"><p className="eyebrow eyebrow-light">HABLEMOS DE TU PROPIEDAD</p><h2>¿Listo para mejorar su <em>rendimiento?</em></h2><Link className="button button-gold" href="/contacto">Contactar <ArrowUpRight size={16} /></Link></div></section></main></GlobalShell> }
function Plan({ name, description, items }: { name: string; description: string; items: string[] }) { return <article className="plan-card"><p className="eyebrow">PLAN DE GESTIÓN</p><h3>{name}</h3><p>{description}</p><div className="check-list">{items.map(item => <span key={item}><Check size={15} /> {item}</span>)}</div><Link className="text-link" href="/contacto">Ver planes <ArrowUpRight size={16} /></Link></article> }
