import Link from 'next/link'
import { Check } from 'lucide-react'
import { ContentPage, SectionBlock, LeadCapture, FAQ, BlogLinks } from '@/components/content-page'
import { contact } from '@/lib/contact'

const legalServices = [
  { title: 'Herencias complejas', copy: 'Asesoramiento integral en procesos de herencias, testamentos y particiones hereditarias con inmuebles.', items: ['Gestión de testamentos', 'Partición de herencias', 'Aceptación y repudio', 'Conflictos entre herederos'] },
  { title: 'Divorcios con inmuebles', copy: 'Resolución de la liquidación de bienes inmuebles en procesos de separación y divorcio.', items: ['Liquidación de gananciales', 'Adjudicación de viviendas', 'Venta de propiedades', 'Uso de vivienda familiar'] },
  { title: 'Problemas registrales', copy: 'Solución de discrepancias entre títulos de propiedad y situación registral real.', items: ['Rectificación de cabida', 'Inmatriculaciones', 'Segregaciones', 'Agrupaciones'] },
  { title: 'Ocupaciones ilegales', copy: 'Recuperación de propiedades ocupadas ilegalmente mediante procedimientos judiciales.', items: ['Desahucios exprés', 'Recuperación de posesión', 'Reclamación de daños', 'Prevención de ocupaciones'] },
  { title: 'Contratos inmobiliarios', copy: 'Redacción y revisión de todo tipo de contratos relacionados con bienes inmuebles.', items: ['Compraventa', 'Arrendamiento', 'Opción de compra', 'Contratos de obra'] },
  { title: 'Impagos y desahucios', copy: 'Reclamación judicial de rentas impagadas y procedimientos de desahucio por falta de pago.', items: ['Reclamación de rentas', 'Desahucios por impago', 'Ejecución de garantías', 'Medidas cautelares'] },
]

export default function DespachoPage() { return <ContentPage eyebrow="Despacho jurídico" title={<>Despacho jurídico especializado en <em>derecho inmobiliario.</em></>} intro="Protegemos tus intereses con asesoramiento legal experto en todas las fases de tu operación inmobiliaria."><SectionBlock title="Nuestros servicios jurídicos"><p>Cobertura legal para tus necesidades inmobiliarias.</p><div className="legal-grid">{legalServices.map(service => <article className="legal-card" key={service.title}><h3>{service.title}</h3><p>{service.copy}</p><ul>{service.items.map(item => <li key={item}><Check size={14} /> {item}</li>)}</ul></article>)}</div></SectionBlock><SectionBlock title="Nuestro proceso"><div className="process-grid"><div><strong>01</strong><h3>Consulta inicial</h3><p>Analizamos tu caso y te ofrecemos un presupuesto sin compromiso.</p></div><div><strong>02</strong><h3>Análisis exhaustivo</h3><p>Estudiamos toda la documentación y elaboramos una estrategia legal.</p></div><div><strong>03</strong><h3>Gestión integral</h3><p>Nos encargamos de todos los trámites legales y administrativos.</p></div><div><strong>04</strong><h3>Resolución efectiva</h3><p>Trabajamos para encontrar la mejor solución para tus intereses.</p></div></div></SectionBlock><section className="content-section content-split"><div className="container content-split-grid"><div><p className="eyebrow">TE ESCUCHAMOS</p><h2>Solicita tu <em>consulta.</em></h2><p>Una primera conversación para entender tu caso y orientarte.</p><div className="why-list"><h3>¿Por qué elegirnos?</h3><div><strong>Especialización inmobiliaria</strong><p>Asesoramiento en derecho inmobiliario y urbanístico.</p></div><div><strong>Atención personalizada</strong><p>Cada caso es único y merece un análisis detallado y soluciones a medida.</p></div><div><strong>Visión integral</strong><p>Combinamos asesoramiento jurídico y experiencia inmobiliaria para proteger tu patrimonio.</p></div></div><FAQ items={['¿Por qué necesito un abogado en mi operación inmobiliaria?', '¿Puedo vender con garantías?', '¿Cómo puedo evitar errores al comprar un piso?']} /><BlogLinks /></div><LeadCapture type="legal" title="Solicita tu consulta" professional /></div></section><section className="final-cta"><div className="container final-cta-inner"><h2>¿Necesitas asesoramiento <em>legal?</em></h2><p>Resuelve tus dudas con una consulta sin compromiso.</p><div className="button-row"><Link className="button button-gold" href="/contacto">Contactar ahora</Link><a className="button button-outline-light" href={contact.phoneHref}>Llamar: {contact.phoneLabel}</a></div></div></section></ContentPage> }
