import Image from 'next/image'
import Link from 'next/link'
import { ArrowRight, ArrowUpRight, BarChart3, Clock3, Home as HomeIcon, LockKeyhole, Scale, Users } from 'lucide-react'
import { GlobalShell } from '@/components/site-shell'
import { ContactDetails, LeadCapture } from '@/components/content-page'
import { QuickValuation } from '@/components/quick-valuation'
import { NewsletterForm } from '@/components/newsletter-form'
import { createClient } from '@/lib/supabase/server'
import { featuredProperties } from '@/lib/properties'

const services = [
  ['Asesoramiento legal', 'Seguridad jurídica en cada operación.'],
  ['Gestión patrimonial', 'Estrategias a medio y largo plazo.'],
  ['Compraventa de inmuebles', 'Gestión integral y acompañamiento.'],
  ['Inversión inmobiliaria', 'Identificación de oportunidades.'],
  ['Valoración de activos', 'Análisis experto del valor de su propiedad.'],
  ['Gestión vacacional', 'Rentabilidad con total tranquilidad.'],
]

export default async function Page() {
  const supabase = await createClient()
  const { data: editorialPosts } = await supabase.from('editorial_posts').select('slug, title, excerpt, category, cover_image_url, published_at').eq('status', 'publicado').not('published_at', 'is', null).order('featured', { ascending: false }).order('published_at', { ascending: false }).limit(3)
  const articles = editorialPosts ?? []

  return <GlobalShell><main id="inicio">
    <section className="hero"><Image src="/grup-ra-hero.png" alt="Interior mediterráneo con piedra y vistas al mar" fill priority sizes="100vw" className="hero-image" /><div className="hero-overlay" /><div className="container hero-content"><p className="eyebrow eyebrow-light">GRUP RA · TARRAGONA</p><h1>Gestionamos,<br />protegemos y<br />rentabilizamos tu <em>patrimonio inmobiliario.</em></h1><p className="hero-copy">Agencia inmobiliaria, despacho jurídico y gestión patrimonial en una única solución.</p><div className="button-row"><Link className="button button-gold" href="#valoracion">Valorar mi propiedad <ArrowUpRight size={17} /></Link><Link className="button button-outline-light" href="#contacto">Hablar con un especialista</Link></div></div></section>

    <section className="quick-strip" aria-label="Servicios Grup RA"><div className="container quick-access-image-wrap"><Image src="/quick-links.png" alt="Despacho Jurídico, Inmobiliaria, Valora tu Inmueble, Gestión Vacacional, Inversión y Actualidad / Blog" width={2048} height={704} sizes="(max-width: 720px) 100vw, 1180px" className="quick-access-image" /></div></section>

    <section className="design-section law-section"><div className="container law-grid"><div><p className="eyebrow">QUIÉNES SOMOS</p><h2>Ley y <em>Patrimonio</em><br />para un mejor mañana.</h2><p>En Grup RA unimos el asesoramiento jurídico y la experiencia inmobiliaria para ofrecerte un servicio integral, cercano y transparente.</p><p>Te acompañamos en cada etapa, protegiendo lo que te importa, maximizando el valor de tu patrimonio y construyendo soluciones seguras, sólidas y duraderas.</p><Link className="text-link" href="/quienes-somos">Conoce Grup RA <ArrowRight size={16} /></Link></div><div className="feature-list">{[['EXPERIENCIA', 'Años de práctica en el ámbito legal e inmobiliario.', Scale], ['VISIÓN INTEGRAL', 'Soluciones conectadas para personas, propiedades y proyectos.', HomeIcon], ['COMPROMISO', 'Un trato cercano, profesional y orientado a resultados.', Users]].map(([title, copy, Icon]) => <div className="feature-item" key={title as string}><span className="round-icon"><Icon size={23} /></span><div><p className="eyebrow">{title as string}</p><p>{copy as string}</p></div></div>)}</div></div></section>

    <section className="design-section properties-new"><div className="container"><div className="section-heading-row"><div><p className="eyebrow">PROPIEDADES DESTACADAS</p><h2>Propiedades <em>que inspiran.</em></h2><p>Descubre una selección de inmuebles únicos en Tarragona y la Costa Daurada.<br />Viviendas con valor, oportunidades de inversión y espacios para disfrutar.</p></div><a className="text-link" href="https://www.advocadarealestate.es/inmuebles" target="_blank" rel="noopener noreferrer">Ver todas las propiedades <ArrowUpRight size={16} /></a></div>{featuredProperties.length > 0 ? <div className="property-grid">{featuredProperties.map(property => <a className="property-card property-card-new" key={property.href} href={property.href} target="_blank" rel="noopener noreferrer"><div className="property-visual"><img src={property.image} alt={property.title} loading="lazy" className="property-photo" /><span>{property.label}</span></div><div className="property-info-new"><p className="eyebrow">{property.location}</p><h3>{property.title}</h3><p>{property.copy}</p><div className="property-meta">{property.meta.map(item => <span key={item}>{item}</span>)}</div><div className="property-price"><strong>{property.price}</strong><span><ArrowRight size={18} /></span></div></div></a>)}</div> : <div className="property-fallback"><p>Consulta toda nuestra cartera de inmuebles en venta y alquiler, actualizada a diario.</p><a className="button button-dark" href="https://www.advocadarealestate.es/inmuebles" target="_blank" rel="noopener noreferrer">Ver nuestras propiedades <ArrowUpRight size={16} /></a></div>}</div></section>

    <section className="design-section valuation-new" id="valoracion"><div className="container valuation-layout"><div className="valuation-intro"><p className="eyebrow">VALORACIÓN RÁPIDA</p><h2>¿Cuánto puede valer<br />tu inmueble?</h2><p>Te ofrecemos una estimación orientativa del valor de tu propiedad, sin compromiso y sin tasación oficial.</p><p className="muted">Completa el formulario y nuestro equipo analizará las características de tu inmueble para ofrecerte una valoración personalizada en el menor tiempo posible.</p><div className="value-benefits"><div><Clock3 /><b>Respuesta en menos de 24h</b><span>Recibe una estimación personalizada.</span></div><div><LockKeyhole /><b>Datos 100% confidenciales</b><span>Tu información está segura.</span></div><div><BarChart3 /><b>Sin compromiso</b><span>Solo una orientación profesional.</span></div></div></div><QuickValuation /></div></section>

    <section className="design-section opportunities"><div className="container opportunities-grid"><div><p className="eyebrow">INVERSORES</p><h2>Oportunidades reales para un <em>patrimonio sólido.</em></h2><p>Acceda a oportunidades de inversión seleccionadas en Tarragona y la Costa Daurada, con análisis, criterio y acompañamiento experto.</p><div className="button-row"><Link className="button button-dark" href="#contacto">Hablar con un especialista <ArrowRight size={16} /></Link><Link className="button button-outline-dark" href="/inversion">Calcular rentabilidad <ArrowRight size={16} /></Link></div></div><div className="opportunity-list">{[['Oportunidades off-market', 'Acceso a inmuebles y proyectos antes de su publicación en portales.'], ['Análisis de rentabilidad', 'Estudios personalizados de ROI, escenarios y viabilidad.'], ['Acompañamiento integral', 'Desde la búsqueda hasta la firma, con soporte legal y fiscal.'], ['Mercado local e internacional', 'Conocimiento del mercado y red de colaboradores en varios países.']].map(([title, copy]) => <div key={title}><h3>{title}</h3><p>{copy}</p></div>)}</div></div></section>

    <section className="design-section expert-section"><div className="container expert-grid"><div><p className="eyebrow">HABLE CON UN ESPECIALISTA</p><h2>Su patrimonio,<br />en manos <em>expertas.</em></h2><p>Le asesoramos de forma personalizada para que tome decisiones seguras y rentables, combinando experiencia jurídica e inmobiliaria.</p><div className="button-row"><Link className="button button-dark" href="#contacto">Hablar con un especialista <ArrowRight size={16} /></Link><Link className="button button-outline-dark" href="/inversion">Calcular rentabilidad <ArrowRight size={16} /></Link></div></div><div><p className="eyebrow">NUESTROS SERVICIOS</p><div className="services-list">{services.map(([title, copy]) => <div key={title}><h3>{title}</h3><p>{copy}</p></div>)}</div></div></div></section>

    {articles.length > 0 && <section className="design-section latest-section"><div className="container"><div className="section-heading-row"><div><p className="eyebrow">ACTUALIDAD</p><h2>Noticias, análisis y tendencias<br />para <em>tu patrimonio.</em></h2><p>Información práctica y actualizada sobre el mercado inmobiliario, novedades legales y oportunidades de inversión en Tarragona y la Costa Daurada.</p></div><Link className="text-link" href="/actualidad">Ver todas las entradas <ArrowRight size={16} /></Link></div><div className="latest-grid">{articles.map(article => <article className="latest-card" key={article.slug}><div className="latest-image">{article.cover_image_url ? <Image src={article.cover_image_url} alt={`Imagen de portada del artículo: ${article.title}`} fill sizes="33vw" /> : <div />}</div><p className="eyebrow">{article.category}</p><h3>{article.title}</h3><p>{article.excerpt}</p><Link className="text-link" href={`/actualidad/${article.slug}`}>Leer artículo <ArrowRight size={16} /></Link></article>)}</div></div></section>}

    <section className="design-section contact-new" id="contacto"><div className="container contact-grid"><div><p className="eyebrow">HABLEMOS</p><h2>Estamos aquí para ayudarte a tomar la <em>mejor decisión.</em></h2><p>Si tienes una idea, una duda o quieres valorar una oportunidad, estaremos encantados de escucharte y asesorarte, sin compromiso.</p><ContactDetails /><div className="newsletter-inline"><p className="eyebrow">RECIBE NUESTRA ACTUALIDAD</p><p>Noticias del mercado, oportunidades de inversión y novedades legales.</p><NewsletterForm /><small>Sin spam. Cancela cuando quieras.</small></div></div><LeadCapture type="contacto" title="Cuéntanos tu proyecto" /></div></section>

    <section className="design-section collaborators"><div className="container"><p className="eyebrow collaborators-title">EMPRESAS COLABORADORAS</p><ul className="collaborators-list">{['Reformas integrales', 'Gestión vacacional', 'Servicios jurídicos', 'Asesoría financiera', 'Mudanzas y vaciados', 'Mantenimiento'].map(item => <li key={item}>{item}</li>)}</ul><Link className="button button-outline-dark" href="/socios">Conoce nuestras empresas colaboradoras <ArrowRight size={16} /></Link></div></section>
  </main></GlobalShell>
}
