'use client'
import { FormEvent, useState } from 'react'
import Link from 'next/link'
import { ArrowRight, ArrowUpRight, Check, Mail, MapPin, Phone, Clock } from 'lucide-react'
import { GlobalShell } from './site-shell'
import { contact } from '@/lib/contact'
export function ContentPage({ eyebrow, title, intro, children }: { eyebrow: string; title: React.ReactNode; intro?: string; children: React.ReactNode }) { return <main className="content-page"><GlobalShell><section className="content-hero"><div className="container"><p className="eyebrow eyebrow-light">{eyebrow}</p><h1>{title}</h1>{intro && <p>{intro}</p>}</div></section>{children}</GlobalShell></main> }
export function SectionBlock({ title, children }: { title: string; children: React.ReactNode }) { return <section className="content-section"><div className="container narrow"><p className="eyebrow">GRUP RA</p><h2>{title}</h2>{children}</div></section> }
export function LinkCta({ href, children }: { href: string; children: React.ReactNode }) { return <Link className="button button-dark" href={href}>{children}<ArrowRight size={16} /></Link> }
export function FeatureList({ items }: { items: string[] }) { return <div className="feature-list">{items.map(item => <span key={item}><Check size={16} />{item}</span>)}</div> }
export function DemoNotice({ children = 'Contenido provisional pendiente de validación.' }: { children?: string }) { return <p className="demo-note">{children}</p> }
export function LeadCapture({ type = 'contacto', title = 'Contacta con nosotros', professional = false }: { type?: string; title?: string; professional?: boolean }) { const [status, setStatus] = useState<'idle'|'pending'|'success'|'error'>('idle'); const [error, setError] = useState(''); async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setStatus('pending'); setError(''); const formElement = event.currentTarget; const form = new FormData(formElement); try { const response = await fetch('/api/leads', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ type, payload: { name: String(form.get('name') ?? '').trim(), email: String(form.get('email') ?? '').trim(), phone: String(form.get('phone') ?? '').trim(), message: String(form.get('message') ?? '').trim() }, sourcePage: window.location.pathname, consentPrivacy: form.get('consentPrivacy') === 'on', honeypot: String(form.get('website') ?? '') }) }); if (!response.ok) { const data = await response.json().catch(() => null); setError(data?.error ?? 'No hemos podido enviar la solicitud.'); setStatus('error'); return } formElement.reset(); setStatus('success') } catch { setError('No hemos podido conectar con el servicio. Inténtalo de nuevo.'); setStatus('error') } } if (status === 'success') return <div className="form-success"><Check size={24} /><strong>Solicitud recibida.</strong><span>Te responderemos lo antes posible.</span></div>; return <form className="content-form" onSubmit={submit}><h2>{title}</h2><label>Nombre completo<input name="name" required minLength={2} /></label><label>Email<input name="email" required type="email" /></label><label>Teléfono<input name="phone" type="tel" /></label><label>{professional ? 'Descripción del caso' : '¿En qué podemos ayudarte?'}<textarea name="message" required minLength={5} rows={5} /></label><label className="honeypot" aria-hidden="true">Website<input name="website" tabIndex={-1} autoComplete="off" /></label><label className="consent-check"><input required type="checkbox" name="consentPrivacy" /><span>Acepto la <Link href="/privacidad">política de privacidad</Link>.</span></label>{professional && <small>El precio de la consulta profesional es de 60€.</small>}{error && <p className="form-error" role="alert">{error}</p>}<button className="button button-gold" type="submit" disabled={status === 'pending'}>{status === 'pending' ? 'Enviando…' : professional ? 'Solicitar consulta' : 'Enviar solicitud'} <ArrowUpRight size={16} /></button></form> }
export const specialties = ['Notarías', 'Gestorías', 'Administradores de fincas', 'Agencias inmobiliarias', 'Constructoras', 'Promotoras', 'Arquitectos', 'Aparejadores', 'Ingenierías', 'Tasadoras']
export function FAQ({ items }: { items: string[] }) { return <div className="faq-list">{items.map(item => <details key={item}><summary>{item}</summary><p>Contenido pendiente de validación y redacción definitiva.</p></details>)}</div> }
export function PageShell({ children }: { children: React.ReactNode }) { return <div className="content-body">{children}</div> }
export function ContactDetails() { return <div className="contact-details">{contact.phones.map(phone => <a key={phone.href} href={phone.href}><Phone />{phone.label}</a>)}{contact.emails.map(email => <a key={email} href={`mailto:${email}`}><Mail />{email}</a>)}<span><MapPin />{contact.address}</span><span><Clock />Horario: {contact.hours.join(' · ')}</span></div> }
export function SimpleCards({ items }: { items: string[] }) { return <div className="simple-cards">{items.map((item, index) => <article key={item}><span>0{index + 1}</span><h3>{item}</h3><p>Asesoramiento especializado y acompañamiento de principio a fin.</p></article>)}</div> }
export function BlogLinks() { return <div className="simple-cards"><article><span>01</span><h3>Derecho inmobiliario</h3><LinkCta href="/actualidad">Ver actualidad</LinkCta></article><article><span>02</span><h3>Gestión vacacional</h3><LinkCta href="/actualidad">Leer artículos</LinkCta></article></div> }
export function RedirectNotice() { return <div className="content-section"><div className="container narrow"><p>La actividad inmobiliaria se encuentra actualmente en la web vinculada a EGO.</p><a className="button button-gold" href="https://www.advocadarealestate.es/inmuebles">Ir a nuestros inmuebles <ArrowUpRight size={16} /></a></div></div> }
export function LegalPending({ title }: { title: string }) { return <ContentPage eyebrow="Información legal" title={title} intro="Esta página está preparada para incorporar el texto legal definitivo proporcionado por Grup RA."><SectionBlock title="Contenido pendiente de validación"><DemoNotice>El contenido jurídico definitivo será incorporado cuando sea facilitado por la empresa. No se muestran cláusulas inventadas.</DemoNotice></SectionBlock></ContentPage> }
